### ISSUE TITLE
Cant built application

### ISSUE THREAD

**Issue by HunterJKirby** [ApolloZhu/Dynamic#8]
I'm getting the errors "diff: /Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation."

**Comment by ApolloZhu** [comment]
Thank you for trying this out!

0. Yes you do need CocoaPods installed, run `pod install`, and open the workspace instead
1. I will try to get back on this after midterm to add instructions for how to build this app
2. when the app has more predictable behaviors, I'll offer direct download then

**Comment by CaptainYukinoshitaHachiman** [comment]
>Thank you for trying this out! ...

@ApolloZhu Don’t forget to add HomeBrew Cask integration XD.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
